"""
pr-pilot: AI-powered GitHub PR reviewer using the Anthropic API.
"""

import os
import sys
import json
import anthropic
from github import Github
from dotenv import load_dotenv

load_dotenv()

# ── Config ────────────────────────────────────────────────────────────────────

ANTHROPIC_API_KEY = os.environ["ANTHROPIC_API_KEY"]
GITHUB_TOKEN      = os.environ["GITHUB_TOKEN"]
GITHUB_REPOSITORY = os.environ["GITHUB_REPOSITORY"]          # e.g. "owner/repo"
PR_NUMBER         = int(os.environ["PR_NUMBER"])
REVIEW_STYLE      = os.environ.get("REVIEW_STYLE", "balanced")  # strict | balanced | lenient
MAX_DIFF_CHARS    = 12_000                                     # keep prompt within token budget

SYSTEM_PROMPT = """You are a senior software engineer performing a pull request code review.

Your review style is: {style}
- strict:   flag every issue, enforce best practices rigorously, suggest refactors
- balanced: highlight real bugs and important improvements, skip trivial nits
- lenient:  focus only on bugs and security issues, be encouraging

Structure your response exactly like this (use these headings):

## Summary
One short paragraph describing what this PR does.

## Issues
List real bugs, logic errors, or security concerns. If none, write "No issues found."

## Suggestions
Actionable improvements (performance, readability, design). If none, write "Looks good."

## Verdict
One of: ✅ Approve | ⚠️ Approve with suggestions | ❌ Request changes

Be direct and specific. Reference file names and line numbers when relevant.
"""

# ── Helpers ───────────────────────────────────────────────────────────────────

def get_pr_diff(repo, pr_number: int) -> str:
    """Fetch the unified diff of a PR, truncated to MAX_DIFF_CHARS."""
    pr = repo.get_pull(pr_number)
    files = pr.get_files()

    diff_parts = []
    for f in files:
        diff_parts.append(f"### {f.filename} ({f.status})")
        if f.patch:
            diff_parts.append(f.patch)

    full_diff = "\n".join(diff_parts)
    if len(full_diff) > MAX_DIFF_CHARS:
        full_diff = full_diff[:MAX_DIFF_CHARS] + "\n\n[diff truncated — too large]"
    return full_diff, pr


def review_diff(diff: str, style: str) -> str:
    """Send the diff to Claude and return the review text."""
    client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)

    message = client.messages.create(
        model="claude-sonnet-4-20250514",
        max_tokens=1024,
        system=SYSTEM_PROMPT.format(style=style),
        messages=[
            {
                "role": "user",
                "content": f"Please review the following pull request diff:\n\n{diff}"
            }
        ]
    )
    return message.content[0].text


def post_comment(pr, review_text: str) -> None:
    """Post the review as a PR comment."""
    header = "## 🤖 pr-pilot Review\n\n"
    footer = "\n\n---\n*Generated by [pr-pilot](https://github.com/marianamartins/pr-pilot)*"
    pr.create_issue_comment(header + review_text + footer)
    print("✅ Review posted successfully.")


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    print(f"🔍 Reviewing PR #{PR_NUMBER} in {GITHUB_REPOSITORY} (style: {REVIEW_STYLE})")

    gh   = Github(GITHUB_TOKEN)
    repo = gh.get_repo(GITHUB_REPOSITORY)

    diff, pr = get_pr_diff(repo, PR_NUMBER)
    if not diff.strip():
        print("⚠️  No diff found — skipping review.")
        sys.exit(0)

    print(f"📄 Diff size: {len(diff)} chars")
    review = review_diff(diff, REVIEW_STYLE)
    post_comment(pr, review)


if __name__ == "__main__":
    main()
